{% set name = "sagemaker" %}
{% set version = "2.245.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/sagemaker/sagemaker-{{ version }}.tar.gz
  sha256: 21af0a8b0baf6dc6e96daa2e539b3fd41d4a4244d69881bce1a343a8fcb7b51a

build:
  noarch: python
  script: echo "[sagemaker-feedstock] intentionally not including any files"
  number: 0

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sagemaker-python-sdk {{ version }}

test:
  imports:
    - sagemaker
  commands:
    - sagemaker-upgrade-v2 --help
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - raybellwaves
